### ISSUE TITLE
About the multiple-sentence results

### ISSUE THREAD

**Issue by RyanLiut** [gyy8426/MSRNN#1]
Hi,

Thanks for your code! Could you provide the multiple-sentence results (prefer), or the best models of the test sets in two datasets, which were reported in the paper? Because I am afraid that there is limited time to reproduce that from scratch.

Thank you!

**Comment by gyy8426** [comment]
We are very honored that you can notice our paper. We add the results on the MSVD dataset to the attachment in https://github.com/gyy8426/MSRNN/blob/master/msrnn.zip, and I think you can use these results in experiments. Unfortunately, we did not save the trained model. Since these codes and files were conducted almost four years ago, I'm not sure if they match the current environment very well. Feel free to ping me if you have any questions.

**Comment by gyy8426** [comment]
We are very honored that you can notice our paper. We add the results on the MSVD dataset to the attachment in https://github.com/gyy8426/MSRNN/blob/master/msrnn.zip, and I think you can use these results in experiments. Unfortunately, we did not save the trained model. Since these codes and files were conducted almost four years ago, I'm not sure if they match the current environment very well. Feel free to ping me if you have any questions.

**Comment by RyanLiut** [comment]
Thank you very much. I wonder: 1) what are the difference between a and b? Just another five runs? 2) Do you still have the results of MSRVTT test results?

**Comment by gyy8426** [comment]
We just test two models with different epochs and different latent stochastic variables. I'm sorry that we lost the results of MSRVTT test results. It is so old and ugly code four years ago.

**Comment by RyanLiut** [comment]
Got it. Many thanks!

**Comment by RyanLiut** [comment]
But if you find the results of MSRVTT later, could you please inform me here？ It would be very grateful.

**Comment by gyy8426** [comment]
You are welcome. Feel free to ping me if you have further questions.
